services:
  redis:
    image: redis/redis-stack:7.4.0-v7
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001" # Insight
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/data
      - ./server/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - pltgm-network

  server:
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - SERVER_PORT=${SERVER_PORT}
      - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - "3000:3000"
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - redis
    volumes:
      - ./server/src:/app/src
    networks:
      - pltgm-network

  client:
    environment:
      - VITE_SERVER_URL=${SERVER_HOST}:${SERVER_PORT}
      - VITE_CLIENT_PORT=${CLIENT_PORT}
    depends_on:
      - server
    ports:
      - "5174:5174"
    build:
      context: client
      dockerfile: Dockerfile
    networks:
      - pltgm-network

volumes:
  redis_data:

networks:
  pltgm-network:
    driver: bridge
